(function(){'use strict';
const DATA='08_DADOS/hermes_training_database_v2.json';let db=null;const state={concertLevel:null,concertId:null};
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
async function load(){try{const r=await fetch(DATA,{cache:'no-store'});if(r.ok)db=await r.json()}catch(e){console.warn('HERMES training DB',e)}if(db)window.HERMES_TRAINING=db}
function methodInfo(id){for(const l of db?.levels||[]){const m=(l.methods||[]).find(x=>x.id===id);if(m)return{...m,level:l.id,levelName:l.name}}return{id,label:id,role:'apoio'}}
function lessonInfo(methodId,lessonId){return db?.methodLessons?.[methodId]?.lessons?.find(l=>l.id===lessonId)||null}
function openLesson(methodId,lessonId){const info=db?.methodLessons?.[methodId],lesson=lessonInfo(methodId,lessonId);if(!info||!lesson||!lesson.verified)return;let url=new URL(info.source,location.href).href;url+='#page='+(lesson.pdfPage||lesson.page);location.href=url}
function openCustomBook(id){const b=(db?.sevcikPersonalizedBooks?.books||[]).find(x=>x.id===id);if(!b||!b.pdf)return;location.href=new URL(b.pdf,location.href).href}
function openMethod(m){const id=m?.method||m?.id;if(String(id).startsWith('SEVCIK_')||String(id).startsWith('SEVCIK'))return showSevcikBooks();const lessons=db?.methodLessons?.[id]?.lessons||[];const first=lessons.find(x=>x.verified);if(first)return openLesson(id,first.id);alert('A lição exata deste método ainda não foi verificada no acervo local. O HERMES não abrirá uma página genérica.')}
function open(){if(!db)return;document.getElementById('ht2')?.remove();const o=document.createElement('div');o.id='ht2';o.className='ht2-overlay';o.innerHTML='<div class="ht2-panel"><div class="ht2-head"><div><div class="ht2-role">HERMES · Formação e Repertório</div><h2 id="ht2-title">Formação</h2></div><button class="ht2-close">Fechar</button></div><div id="ht2-body"></div></div>';document.body.appendChild(o);o.querySelector('.ht2-close').onclick=()=>o.remove();showFormation()}
const levelNames={L1:'Iniciante — Fundação',L2:'Iniciante — Primeiros Concertos',L3:'Intermédio inicial — Vivaldi',L4:'Intermédio — Transição',L5:'Avançado',L6:'Pré-solista / Solista'};
function showStudies(){
 const b=document.querySelector('#ht2-body'); if(!b)return;
 const books=db?.sevcikPersonalizedBooks?.books||[];
 const find=id=>books.find(x=>x.id===id);
 const left=[['HSEV_TERCAS','Tercas'],['HSEV_QUARTAS','Quartas'],['HSEV_SEXTAS','Sextas'],['HSEV_DECIMAS','Decimas'],['HSEV_OITAVAS','Oitavas']];
 const right=[['HSEV_ARCO_BASE','Arco - Base e golpes fundamentais']];
 const render=(title,items)=>'<div class=\"ht2-card\"><h3>'+title+'</h3><div class=\"ht2-methods\">'+items.map(([id,label])=>{const x=find(id);return x?'<div class=\"ht2-method\"><button data-study-book=\"'+id+'\"><strong>'+label+'</strong><br><span class=\"ht2-muted\">Sequencia: '+x.sequence.join(' -> ')+'</span><br><span class=\"ht2-tag\">PDF personalizado HERMES</span></button></div>':'';}).join('')+'</div></div>';
 b.innerHTML='<p>Estudos tecnicos. O metodo nao aparece como album completo. Cada botao abre um PDF HERMES reorganizado com somente a sequencia selecionada.</p>'+render('MAO ESQUERDA - CORDAS DUPLAS',left)+render('MAO DIREITA - ARCO',right)+'<div class="ht2-card"><h3>Outras familias</h3><p class="ht2-note">Escalas, mudancas de posicao, quintas e outras familias entram aqui depois da indexacao das respectivas edicoes Sevcik. O HERMES nao cria sequencias por suposicao.</p></div>';
 b.querySelectorAll('[data-study-book]').forEach(x=>x.onclick=()=>openCustomBook(x.dataset.studyBook));
}
function showFormation(){const b=document.querySelector('#ht2-body');b.innerHTML='<p>Os níveis mostram o que deve ser construído. O aluno não precisa estudar tudo de uma vez: o HERMES libera gradualmente conforme as competências.</p><div class="ht2-levels">'+db.levels.map((l,i)=>'<div class="ht2-card"><button data-level="'+l.id+'" class="'+(i===0?'active':'')+'"><strong>'+esc(levelNames[l.id]||l.name)+'</strong><br><span class="ht2-muted">'+l.methods.length+' rotas de método</span></button></div>').join('')+'</div><div id="ht2-level-detail"></div>';document.querySelectorAll('#ht2 [data-level]').forEach(x=>x.onclick=()=>{document.querySelectorAll('#ht2 [data-level]').forEach(y=>y.classList.remove('active'));x.classList.add('active');renderLevel(x.dataset.level)});renderLevel(db.levels[0].id)}
function renderLevel(id){const l=db.levels.find(x=>x.id===id),box=document.querySelector('#ht2-level-detail');if(!l||!box)return;box.innerHTML='<div class="ht2-card"><h3>'+esc(levelNames[id]||l.name)+'</h3><p class="ht2-muted">Ordem pedagógica: <b>Ševčík primeiro</b> → complemento → repertório → avaliação.</p><div class="ht2-methods">'+l.methods.map(m=>'<div class="ht2-method"><button data-method="'+esc(m.id)+'"><strong>'+esc(m.label)+'</strong><br><span class="ht2-role">'+esc(m.role||'método')+'</span>'+(m.status==='local_pdf'?'<span class="ht2-tag">PDF local</span>':'')+(m.status==='missing_pdf'?'<span class="ht2-tag">PDF a adquirir</span>':'')+'</button></div>').join('')+'</div></div>';box.querySelectorAll('[data-method]').forEach(x=>x.onclick=()=>{if(String(x.dataset.method).startsWith('SEVCIK'))showSevcikBooks();else showMethodDetail(x.dataset.method)})}
function showSevcikBooks(){const box=document.querySelector('#ht2-level-detail');if(!box)return;const bs=db?.sevcikPersonalizedBooks?.books||[];box.insertAdjacentHTML('beforeend','<div class="ht2-card ht2-method-detail"><h3>Ševčík — Cadernos personalizados HERMES</h3><p class="ht2-note"><b>Regra:</b> não estudar o álbum inteiro. O HERMES separa apenas as lições necessárias e coloca-as numa sequência progressiva/intercalada.</p><div class="ht2-methods">'+bs.map(b=>'<div class="ht2-method"><button data-custom-book="'+esc(b.id)+'"><strong>'+esc(b.title)+'</strong><br><span class="ht2-role">'+esc(b.sourceMethod)+'</span><br><span class="ht2-muted">Exercícios: '+esc((b.sequence||[]).join(' → '))+'</span></button></div>').join('')+'</div><p class="ht2-note">Categorias ainda não montadas ficam bloqueadas até a edição correspondente ser indexada; HERMES não cria sequência por suposição.</p></div>');box.querySelectorAll('[data-custom-book]').forEach(x=>x.onclick=()=>openCustomBook(x.dataset.customBook))}
function showMethodDetail(id){const m=methodInfo(id),box=document.querySelector('#ht2-level-detail');if(!box)return;const lessons=db?.methodLessons?.[id]?.lessons||[],rows=lessons.filter(x=>x.verified).map(x=>'<div class="ht2-support-row"><div><b>'+esc(x.exercise)+'</b><br><span class="ht2-muted">PDF p. '+esc(x.pdfPage||x.page)+(x.pageEnd?'–'+esc(x.pageEnd):'')+' · '+esc(x.description)+'</span>'+(x.study?'<br><span class="ht2-note"><b>Como estudar:</b> '+esc(x.study)+'</span>':'')+'</div><button class="ht2-open" data-lesson="'+esc(x.id)+'">Abrir lição exata</button></div>').join('');box.insertAdjacentHTML('beforeend','<div class="ht2-card ht2-method-detail"><h3>'+esc(m.label)+'</h3><p>'+esc(m.role||'')+'</p><p class="ht2-note"><b>Regra:</b> o HERMES abre a lição, não uma página genérica do método.</p><div class="ht2-support">'+(rows||'<p class="ht2-note">Ainda não há lição verificada para este método.</p>')+'</div></div>');box.querySelectorAll('[data-lesson]').forEach(x=>x.onclick=()=>openLesson(id,x.dataset.lesson))}
function showConcerts(){const b=document.querySelector('#ht2-body'),levels=[...new Set(db.concerts.map(c=>c.level))];b.innerHTML='<p>Escolha o nível. Depois o concerto. Dentro: movimento → trecho crítico → competência → lição exata → retorno à música.</p><div class="ht2-levels">'+levels.map((l,i)=>'<div class="ht2-card"><button data-clevel="'+l+'" class="'+(i===0?'active':'')+'"><strong>'+esc(levelNames[l]||l)+'</strong><br><span class="ht2-muted">'+db.concerts.filter(c=>c.level===l).length+' concertos</span></button></div>').join('')+'</div><div id="ht2-concerts"></div>';document.querySelectorAll('[data-clevel]').forEach(x=>x.onclick=()=>{state.concertLevel=x.dataset.clevel;document.querySelectorAll('[data-clevel]').forEach(y=>y.classList.remove('active'));x.classList.add('active');renderConcertLevel(x.dataset.clevel)});state.concertLevel=levels[0];renderConcertLevel(levels[0])}
function renderConcertLevel(level){state.concertLevel=level;const cs=db.concerts.filter(c=>c.level===level),box=document.querySelector('#ht2-concerts');box.innerHTML='<div class="ht2-sessions">'+cs.map(c=>'<div class="ht2-card"><button data-concert="'+c.id+'"><strong>'+esc(c.title)+'</strong><br><span class="ht2-muted">'+esc(c.tonality||'')+' · '+c.sessions.length+' sessões</span></button></div>').join('')+'</div>';box.querySelectorAll('[data-concert]').forEach(x=>x.onclick=()=>{state.concertId=x.dataset.concert;renderConcert(x.dataset.concert)})}
function renderConcert(id){const c=db.concerts.find(x=>x.id===id),box=document.querySelector('#ht2-concerts');if(!c)return;state.concertId=id;box.innerHTML='<div class="ht2-card"><button class="ht2-open" id="ht2-back">← Voltar para '+esc(levelNames[c.level]||c.level)+'</button><h2>'+esc(c.title)+'</h2><p><b>Tonalidade:</b> '+esc(c.tonality||'')+'</p><p class="ht2-note">Mapeamento musical: '+esc(c.mappingStatus||'needs_score_mapping')+'.</p><h3>Movimentos / sessões</h3><div class="ht2-sessions">'+c.sessions.map(s=>'<div class="ht2-card"><button data-session="'+s.id+'"><strong>'+esc(s.title)+'</strong><br><span class="ht2-muted">'+esc(s.focus)+'</span></button></div>').join('')+'</div><div id="ht2-session"></div></div>';document.getElementById('ht2-back').onclick=()=>renderConcertLevel(state.concertLevel||c.level);box.querySelectorAll('[data-session]').forEach(x=>x.onclick=()=>renderSession(c,x.dataset.session))}
function renderSession(c,sid){const s=c.sessions.find(x=>x.id===sid),box=document.querySelector('#ht2-session');if(!s)return;const m=s.support?.[0],lesson=m?.lessonId?lessonInfo(m.method,m.lessonId):null;box.innerHTML='<div class="ht2-critical"><div class="ht2-role">TRECHO CRÍTICO SELECIONADO</div><h3>'+esc(s.title)+'</h3><p><b>Trecho:</b> '+esc(s.critical)+'</p><p><b>Foco:</b> '+esc(s.focus)+'</p><p><b>Problemas:</b> '+s.problems.map(esc).join(' · ')+'</p><div class="ht2-selection"><b>Seleção técnica</b><span>O HERMES marca este trecho como foco da sessão. Compassos exatos ficam vinculados à edição local quando validados.</span></div></div><h3>Método de apoio — lição exata</h3><div class="ht2-support">'+s.support.map((x,i)=>{const li=x.lessonId?lessonInfo(x.method,x.lessonId):null;return '<div class="ht2-support-row '+(i===0?'ht2-primary':'')+'"><strong>'+esc(x.priority)+'</strong><div><b>'+esc(methodInfo(x.method).label)+'</b><br><span class="ht2-muted">'+esc(x.lesson||'')+(li?' · PDF p. '+(li.pdfPage||li.page)+(li.pageEnd?'–'+li.pageEnd:''):'')+'</span>'+(x.verified?'<br><span class="ht2-tag">lição verificada</span>':'<br><span class="ht2-tag">rota a verificar</span>')+(x.study?'<br><span class="ht2-note"><b>Como estudar:</b> '+esc(x.study)+'</span>':'')+'</div>'+(x.verified&&x.lessonId?'<button class="ht2-open" data-open-lesson="'+esc(x.lessonId)+'" data-method="'+esc(x.method)+'">Abrir lição exata</button>':'<span class="ht2-tag">lição exata ainda não verificada — sem link genérico</span>')+'</div>'}).join('')+'</div>';box.querySelectorAll('[data-open-lesson]').forEach(x=>x.onclick=()=>openLesson(x.dataset.method||s.support[0].method,x.dataset.openLesson));box.querySelectorAll('[data-open-method]').forEach(x=>x.onclick=()=>openMethod({id:x.dataset.openMethod}))}
function openFormation(){open()}
function openConcerts(){if(!db)return;open();document.querySelector('#ht2-title').textContent='Concertos';showConcerts()}
window.HERMES_TRAINING_UI={open:openFormation,openConcerts,openStudies:()=>{open();document.querySelector('#ht2-title').textContent='Estudos';showStudies()}};
document.addEventListener('DOMContentLoaded',load);
})();



