(function(){'use strict';
const DATA='08_DADOS/hermes_training_database_v2.json';let db=null;
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
async function load(){try{const r=await fetch(DATA,{cache:'no-store'});if(r.ok)db=await r.json()}catch(e){} if(db)window.HERMES_TRAINING=db}
function methodInfo(id){const levels=db?.levels||[];for(const l of levels){const m=l.methods.find(x=>x.id===id);if(m)return {...m,level:l.id,levelName:l.name}}return {id,label:id,role:'apoio'}}
function openMethod(m){const info=methodInfo(m.method||m.id);const file=db.methodFiles?.[info.id]?.file;const publicUrl=file?file:null;let url=info.source||null;if(publicUrl)url=publicUrl;const page=m.page?('#page='+m.page):'';if(publicUrl)url=publicUrl+page;else if(info.source)url=info.source;const w=window.open(url,'_blank','noopener');if(!w&&url)location.href=url}
function open(){if(!db)return;let old=document.getElementById('ht2');if(old)old.remove();const o=document.createElement('div');o.id='ht2';o.className='ht2-overlay';o.innerHTML='<div class="ht2-panel"><div class="ht2-head"><div><div class="ht2-role">HERMES · Formação e Repertório</div><h2 id="ht2-title">Formação</h2></div><button class="ht2-close">Fechar</button></div><div id="ht2-body"></div></div>';document.body.appendChild(o);o.querySelector('.ht2-close').onclick=()=>o.remove();showFormation()}
function showFormation(){const b=document.querySelector('#ht2-body');b.innerHTML='<p>Os níveis mostram o que deve ser construído. O aluno não precisa estudar tudo de uma vez: o HERMES libera gradualmente conforme as competências.</p><div class="ht2-levels">'+db.levels.map((l,i)=>'<div class="ht2-card"><button data-level="'+l.id+'" class="'+(i===0?'active':'')+'"><strong>'+esc(l.name)+'</strong><br><span class="ht2-muted">'+l.methods.length+' rotas de método</span></button></div>').join('')+'</div><div id="ht2-level-detail"></div>';oHandlers();renderLevel(db.levels[0].id)}
function oHandlers(){document.querySelectorAll('#ht2 .ht2-levels button').forEach(x=>x.onclick=()=>{document.querySelectorAll('#ht2 .ht2-levels button').forEach(y=>y.classList.remove('active'));x.classList.add('active');renderLevel(x.dataset.level)})}
function renderLevel(id){const l=db.levels.find(x=>x.id===id),box=document.querySelector('#ht2-level-detail');if(!l||!box)return;box.innerHTML='<div class="ht2-card"><h3>'+esc(l.name)+'</h3><p class="ht2-muted">Ordem pedagógica: <b>Ševčík primeiro</b> → complemento → repertório → avaliação.</p><div class="ht2-methods">'+l.methods.map(m=>'<div class="ht2-method"><button data-method="'+esc(m.id)+'"><strong>'+esc(m.label)+'</strong><br><span class="ht2-role">'+esc(m.role||'método')+'</span>'+(m.status==='local_pdf'?'<span class="ht2-tag">PDF local</span>':'')+(m.status==='missing_pdf'?'<span class="ht2-tag">PDF a adquirir</span>':'')+'</button></div>').join('')+'</div></div>';box.querySelectorAll('[data-method]').forEach(x=>x.onclick=()=>showMethodDetail(x.dataset.method))}
function showMethodDetail(id){const m=methodInfo(id),box=document.querySelector('#ht2-level-detail');if(!box)return;box.insertAdjacentHTML('beforeend','<div class="ht2-card ht2-method-detail"><h3>'+esc(m.label)+'</h3><p>'+esc(m.role||'')+'</p><p class="ht2-note">O método só entra como treino dirigido. A lição exata será aberta a partir do trecho quando estiver mapeada para a edição usada.</p>'+(m.source?'<button class="ht2-open" id="ht2-source">Abrir fonte</button>':'')+'</div>');document.getElementById('ht2-source')?.addEventListener('click',()=>window.open(m.source,'_blank'))}
function showConcerts(){const b=document.querySelector('#ht2-body');b.innerHTML='<p>Primeiro escolhemos o nível. Depois o concerto. Dentro do concerto: movimento → sessão → trecho crítico → competência → <b>1ª opção Ševčík</b> → outras opções.</p><div class="ht2-levels">'+[...new Set(db.concerts.map(c=>c.level))].map((l,i)=>'<div class="ht2-card"><button data-clevel="'+l+'" class="'+(i===0?'active':'')+'"><strong>'+({L1:'Iniciante — Fundação',L2:'Iniciante — Primeiros Concertos',L3:'Intermédio inicial — Vivaldi',L4:'Intermédio',L5:'Avançado'}[l]||l)+'</strong></button></div>').join('')+'</div><div id="ht2-concerts"></div>';document.querySelectorAll('[data-clevel]').forEach(x=>x.onclick=()=>renderConcertLevel(x.dataset.clevel));renderConcertLevel(db.concerts[0].level)}
function renderConcertLevel(level){const cs=db.concerts.filter(c=>c.level===level),box=document.querySelector('#ht2-concerts');box.innerHTML='<div class="ht2-sessions">'+cs.map(c=>'<div class="ht2-card"><button data-concert="'+c.id+'"><strong>'+esc(c.title)+'</strong><br><span class="ht2-muted">'+c.sessions.length+' sessões</span></button></div>').join('')+'</div>';box.querySelectorAll('[data-concert]').forEach(x=>x.onclick=()=>renderConcert(x.dataset.concert))}
function renderConcert(id){const c=db.concerts.find(x=>x.id===id),box=document.querySelector('#ht2-concerts');if(!c)return;box.innerHTML='<div class="ht2-card"><button class="ht2-open" id="ht2-back">← Concertos do nível</button><h2>'+esc(c.title)+'</h2><p><a href="'+esc(c.source)+'" target="_blank" rel="noopener">Fonte pública da partitura</a></p><h3>Concerto trabalhado</h3><div class="ht2-sessions">'+c.sessions.map(s=>'<div class="ht2-card"><button data-session="'+s.id+'"><strong>'+esc(s.title)+'</strong><br><span class="ht2-muted">'+esc(s.focus)+'</span></button></div>').join('')+'</div><div id="ht2-session"></div></div>';document.getElementById('ht2-back').onclick=()=>renderConcertLevel(c.level);box.querySelectorAll('[data-session]').forEach(x=>x.onclick=()=>renderSession(c,x.dataset.session))}
function renderSession(c,sid){const s=c.sessions.find(x=>x.id===sid),box=document.querySelector('#ht2-session');if(!s)return;box.innerHTML='<div class="ht2-critical"><div class="ht2-role">TRECHO CRÍTICO SUBLINHADO</div><h3>'+esc(s.title)+'</h3><p><b>Área:</b> '+esc(s.critical)+'</p><p><b>Foco:</b> '+esc(s.focus)+'</p><p><b>Problemas:</b> '+s.problems.map(esc).join(' · ')+'</p><p class="ht2-note">Esta é a ponte que faltava: o trecho não fica sozinho. Ele chama uma lição técnica antes do retorno à música.</p></div><h3>Métodos de apoio</h3><div class="ht2-support">'+s.support.map((m,i)=>'<div class="ht2-support-row '+(i===0?'ht2-primary':'')+'"><strong>'+esc(m.priority)+'</strong><div><b>'+esc(methodInfo(m.method).label)+'</b><br><span class="ht2-muted">'+esc(m.lesson)+'</span>'+(m.verified?'<br><span class="ht2-tag">mapeamento verificado</span>':'<br><span class="ht2-tag">mapeamento pedagógico — verificar edição/página</span>')+'</div><button class="ht2-open" data-open-method="'+esc(m.method)+'" data-page="'+(m.page||'')+'">Abrir lição</button></div>').join('')+'</div>';box.querySelectorAll('[data-open-method]').forEach(x=>x.onclick=()=>openMethod({method:x.dataset.openMethod,page:x.dataset.page||null}))}
function openFormation(){open()}
function openConcerts(){if(!db)return;open();document.querySelector('#ht2-title').textContent='Concertos';showConcerts()}
window.HERMES_TRAINING_UI={open:openFormation,openConcerts};
document.addEventListener('DOMContentLoaded',()=>load());
})();