/* HERMES Placement Assessment v2 — prova adaptativa, monitorização ao vivo + gravação local */
(function(){
"use strict";
const DATA="08_DADOS/hermes_placement_assessment_v1.json",KEY="hermes_placement_v2";
let db=null,state={level:0,task:0,results:[],stream:null,ctx:null,analyser:null,raf:null,rec:null,chunks:[],running:false,started:0};
const esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
async function load(){try{const r=await fetch(DATA,{cache:"no-store"});if(r.ok)db=await r.json();}catch(e){}if(db)render();}
function render(){if(document.getElementById("hermes-placement-panel"))return;const host=document.querySelector("#hermes-formation-panel")||document.querySelector("main");if(!host)return;const p=document.createElement("section");p.id="hermes-placement-panel";p.className="panel no-print";p.innerHTML='<div class="panel-header"><h2 class="panel-title">🎓 HERMES — Prova de Nivelamento</h2><span class="badge">MICROFONE LOCAL</span></div><p>Você não informa o seu nível. O HERMES apresenta <strong>escala + estudo + peça</strong>, ouve ao vivo e grava a execução apenas no dispositivo. Depois analisa os dados e decide se sobe, mantém ou desce o nível.</p><div id="hermes-placement-task"></div><div class="hermes-placement-actions"><button id="hermes-placement-start" class="btn btn-primary btn-sm">🎙️ Começar trecho</button><button id="hermes-placement-stop" class="btn btn-secondary btn-sm" disabled>⏹ Terminar trecho</button></div><div id="hermes-placement-live"></div><div id="hermes-placement-result"></div>';host.parentNode.insertBefore(p,host.nextSibling);showTask();p.querySelector("#hermes-placement-start").onclick=start;p.querySelector("#hermes-placement-stop").onclick=stop;}
function current(){const l=db.levels[state.level];return state.task===0?l.scale:state.task===1?l.study:l.piece;}
function showTask(){const l=db.levels[state.level],x=current(),type=state.task===0?"ESCALA":state.task===1?"ESTUDO":"PEÇA",box=document.getElementById("hermes-placement-task");if(!box)return;box.innerHTML='<div class="hermes-placement-card"><div class="badge">NÍVEL '+esc(l.id)+' · '+esc(l.name)+' · '+type+'</div><h3>'+esc(x.work)+'</h3><p><strong>Faça exatamente:</strong> '+esc(x.task)+'</p><p><strong>O HERMES observa:</strong> '+esc(x.focus.join(" · "))+'</p><p><strong>Regra:</strong> toque como numa audição normal. Não tente “provar” que é avançado. Qualidade e naturalidade são o teste.</p></div>';}
function pitch(buf,sr){let rms=Math.sqrt(buf.reduce((a,x)=>a+x*x,0)/buf.length);if(rms<.012)return null;let best=0,bc=0,min=Math.floor(sr/1200),max=Math.min(Math.floor(sr/120),buf.length-2);for(let lag=min;lag<=max;lag++){let s=0,n=0;for(let i=0;i<buf.length-lag;i+=2){s+=buf[i]*buf[i+lag];n++;}let c=s/n;if(c>bc){bc=c;best=lag;}}return best&&bc>.001?sr/best:null;}
function frame(){if(!state.running)return;const b=new Float32Array(state.analyser.fftSize);state.analyser.getFloatTimeDomainData(b);const hz=pitch(b,state.ctx.sampleRate);if(hz){state.recMetrics.voiced++;state.recMetrics.pitches.push(hz);}state.recMetrics.frames++;document.getElementById("hermes-placement-live").textContent=hz?"🎙️ A ouvir • "+hz.toFixed(1)+" Hz • gravação local ativa":"🎙️ Aguardando som… • gravação local ativa";state.raf=requestAnimationFrame(frame);}
async function start(){if(state.running)return;try{state.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});state.ctx=new (window.AudioContext||window.webkitAudioContext)();await state.ctx.resume();const src=state.ctx.createMediaStreamSource(state.stream);state.analyser=state.ctx.createAnalyser();state.analyser.fftSize=4096;src.connect(state.analyser);state.chunks=[];state.rec=null;if(window.MediaRecorder){try{state.rec=new MediaRecorder(state.stream);state.rec.ondataavailable=e=>{if(e.data.size)state.chunks.push(e.data);};state.rec.start(250);}catch(e){}}state.recMetrics={frames:0,voiced:0,pitches:[]};state.running=true;state.started=performance.now();document.getElementById("hermes-placement-start").disabled=true;document.getElementById("hermes-placement-stop").disabled=false;frame();}catch(e){document.getElementById("hermes-placement-live").textContent="Erro de microfone: "+e.message;}}
function analyze(){const m=state.recMetrics,v=m.voiced/Math.max(1,m.frames),p=m.pitches;let stability=0;if(p.length>3){let ds=[];for(let i=1;i<p.length;i++)ds.push(Math.abs(1200*Math.log2(p[i]/p[i-1])));ds.sort((a,b)=>a-b);const med=ds[Math.floor(ds.length/2)]||0;stability=Math.max(0,Math.min(1,1-med/100));}const duration=(performance.now()-state.started)/1000;return{durationSec:+duration.toFixed(1),voicedRatio:+v.toFixed(3),pitchStability:+stability.toFixed(3),rawFrames:m.frames,localRecording:!!state.chunks.length};}
async function saveLocalRecording(){if(!state.chunks.length)return false;try{const blob=new Blob(state.chunks,{type:state.rec?.mimeType||"audio/webm"});const dbx=await new Promise((resolve,reject)=>{const q=indexedDB.open("hermes_placement_recordings",1);q.onupgradeneeded=()=>q.result.createObjectStore("takes",{autoIncrement:true});q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});await new Promise((resolve,reject)=>{const tx=dbx.transaction("takes","readwrite");tx.objectStore("takes").add({timestamp:new Date().toISOString(),level:db.levels[state.level].id,task:["scale","study","piece"][state.task],blob});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});dbx.close();return true;}catch(e){return false;}}
async function stop(){if(!state.running)return;state.running=false;cancelAnimationFrame(state.raf);if(state.rec&&state.rec.state!=="inactive")state.rec.stop();state.stream?.getTracks().forEach(t=>t.stop());state.ctx?.close();await new Promise(r=>setTimeout(r,300));const saved=await saveLocalRecording();const metrics=analyze();metrics.localRecording=saved;const level=db.levels[state.level];state.results.push({level:level.id,levelName:level.name,task:["scale","study","piece"][state.task],metrics});document.getElementById("hermes-placement-start").disabled=false;document.getElementById("hermes-placement-stop").disabled=true;document.getElementById("hermes-placement-live").textContent="Trecho guardado localmente • "+metrics.durationSec+" s";advance();}
function taskScore(r){return Math.max(0,Math.min(1,r.metrics.voicedRatio*.45+r.metrics.pitchStability*.55));}
function levelResults(id){return state.results.filter(r=>r.level===id);}
function levelScore(id){const a=levelResults(id);return a.length? a.reduce((s,r)=>s+taskScore(r),0)/a.length:0;}
function advance(){if(state.task<2){state.task++;showTask();return;}const s=levelScore(db.levels[state.level].id);if(s>=db.adaptiveExam.passThreshold&&state.level<db.levels.length-1){state.level++;state.task=0;showTask();return;}finish(s);}
function finish(score){const idx=Math.max(0,state.level-(score>=db.adaptiveExam.passThreshold?0:1));const demonstrated=db.levels[idx];const confidence=score>=db.adaptiveExam.strongThreshold?"alta":score>=db.adaptiveExam.passThreshold?"média":"baixa";const result={timestamp:new Date().toISOString(),demonstratedLevel:demonstrated.id,demonstratedName:demonstrated.name,confidence,score:+score.toFixed(3),tasks:state.results,provisional:true,note:"A classificação definitiva será recalculada quando ritmo, ataques, duração, articulação e comparação com partitura estiverem ativos."};localStorage.setItem(KEY,JSON.stringify(result));document.getElementById("hermes-placement-result").innerHTML='<div class="hermes-placement-result"><h3>📋 Resultado provisório</h3><p><strong>Nível demonstrado:</strong> '+esc(demonstrated.name)+'</p><p><strong>Confiança:</strong> '+confidence+'</p><p><strong>Pontuação técnica atualmente mensurável:</strong> '+Math.round(score*100)+'%</p><p>O resultado não é baseado no que você declarou. O HERMES testou o nível por etapas e parou quando encontrou o primeiro nível sem evidência suficiente para avançar.</p><p><strong>Importante:</strong> nesta versão, a parte de áudio mede principalmente presença, altura e estabilidade de pitch. O motor de ritmo/onset/articulação ainda precisa entrar para transformar isto numa avaliação completa.</p></div>';window.dispatchEvent(new CustomEvent("hermes:placement-result",{detail:result}));}
window.HERMES_PLACEMENT={start,stop,getResult:()=>JSON.parse(localStorage.getItem(KEY)||"null")};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",load,{once:true});else load();
})();